print('hello world')
print('the answer is', 4 + 6, '.')
print(9 + 1)
print('9+1=', 9+1, '.')
print('hi', 'there', sep='\n')
f=open('hello.txt', 'w')
print("hi Zach", file=f)
ans=input('how are you?')
print('good how are you')
print('im fine')
print('glad you are', ans,'.', sep="")
print(len(ans))
print('hi', 9, '.')
print(max(90,91,84))
feeling=input('how do you feel?')
print(len('Jared'))
x=5
