# first_num = input('enter first number')
# second_num = input('enter second number')
# third_num = input('enter third number')
# print(int(first_num) * int(second_num))
# print(int(first_num) * int(second_num) / int(third_num))
# num = input('pick a number')
# print(int(num) % 2 == 0)
# money = input('how much money will you be taking with you on vacation?')
# print('you will have', end=' ')
# print(int(money) * .86)
# print(7 > 5 and 'b' > 'd')
# print(7+5 and 'b' + 'd')
# print(7 * 5 or 'b' * 'd')
# name = input('what is your name?')
# print(ord(name[0]))
# word = input('pick any word')
# print(word, 'is a great word')
# ques = input('do you like that word')
# # print('i agree')
# # print(pow(4,2))
# # print(sum((3,5,2)))
# a=8
# print(isinstance(a, int))
# print(vars())
# print(id(a))